import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.getStarted': 'Get Started',
    'nav.login': 'Sign In',
    'nav.signup': 'Sign Up',
    'nav.pricing': 'Pricing',
    
    // Landing Page
    'landing.hero.title': 'Transform Reports into',
    'landing.hero.podcast': 'Podcasts',
    'landing.hero.subtitle': 'No more reading lengthy reports. With ReportCast, your documents become listenable podcasts.',
    'landing.hero.cta': 'Get Started',
    'landing.hero.howItWorks': 'How It Works?',
    
    'landing.how.title': 'How It Works?',
    'landing.how.subtitle': 'Transform your reports into podcasts in 3 simple steps',
    'landing.how.step1.title': '1. Upload Report',
    'landing.how.step1.desc': 'Upload your report in PDF format. We support documents up to 50 pages.',
    'landing.how.step2.title': '2. Convert to Podcast',
    'landing.how.step2.desc': 'Our AI technology transforms your report into a natural and listenable podcast.',
    'landing.how.step3.title': '3. Share',
    'landing.how.step3.desc': 'Share the generated public link with your team. Anyone can listen anytime, anywhere.',
    
    'landing.features.title': 'Why ReportCast?',
    'landing.features.subtitle': 'Make learning more accessible',
    'landing.features.listen.title': 'Listen Everywhere',
    'landing.features.listen.desc': 'While driving, exercising, or traveling - you can now listen to reports anywhere.',
    'landing.features.fast.title': 'Fast Conversion',
    'landing.features.fast.desc': 'Our AI-powered system converts your reports into professional podcasts in seconds.',
    'landing.features.secure.title': 'Secure Sharing',
    'landing.features.secure.desc': 'Share with public links in a controlled manner. You can disable links anytime.',
    
    'landing.cta.title': 'Ready to get started?',
    'landing.cta.subtitle': 'Start now to convert your first report into a podcast',
    'landing.cta.button': 'Start Free',
    
    'landing.footer': '© 2026 ReportCast. All rights reserved.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.upload.title': 'Upload New Report',
    'dashboard.upload.desc': 'Convert your report into a podcast',
    'dashboard.upload.label': 'Report File',
    'dashboard.upload.placeholder': 'No file selected',
    'dashboard.upload.button': 'Upload & Convert',
    'dashboard.upload.success': 'Report uploaded successfully! Converting to podcast...',
    'dashboard.reports.title': 'Your Podcasts',
    'dashboard.reports.status.pending': 'Pending',
    'dashboard.reports.status.processing': 'Processing',
    'dashboard.reports.status.ready': 'Ready',
    'dashboard.reports.status.completed': 'Completed',
    'dashboard.reports.status.failed': 'Failed',
    'dashboard.reports.duration': 'min',
    'dashboard.reports.views': 'plays',
    'dashboard.reports.share': 'Share Link',
    'dashboard.reports.listen': 'Listen',
    'dashboard.reports.delete': 'Delete',
    'dashboard.copy.success': 'Share link copied to clipboard!',
    'dashboard.delete.success': 'Podcast deleted successfully',
    'dashboard.confirm.title': 'Confirm Processing',
    'dashboard.confirm.message': 'Cost',
    'dashboard.confirm.button': 'Confirm & Process',
    
    // Podcast Player
    'podcast.backToDashboard': 'Back to Dashboard',
    'podcast.generatedBy': 'Generated by ReportCast',
    'podcast.share': 'Share',
    'podcast.shareTitle': 'Share This Podcast',
    'podcast.shareDesc': 'Anyone with this link can listen to this podcast',
    'podcast.copyLink': 'Copy Link',
    'podcast.cancel': 'Cancel',
    
    // Auth Pages
    'auth.login.title': 'Welcome Back',
    'auth.login.subtitle': 'Sign in to your ReportCast account',
    'auth.login.email': 'Email',
    'auth.login.password': 'Password',
    'auth.login.button': 'Sign In',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.signUp': 'Sign up',
    'auth.login.forgotPassword': 'Forgot password?',
    
    'auth.signup.title': 'Create Account',
    'auth.signup.subtitle': 'Start converting reports to podcasts',
    'auth.signup.name': 'Full Name',
    'auth.signup.email': 'Email',
    'auth.signup.password': 'Password',
    'auth.signup.confirmPassword': 'Confirm Password',
    'auth.signup.button': 'Create Account',
    'auth.signup.hasAccount': 'Already have an account?',
    'auth.signup.signIn': 'Sign in',
    'auth.signup.terms': 'By signing up, you agree to our',
    'auth.signup.termsLink': 'Terms of Service',
    'auth.signup.and': 'and',
    'auth.signup.privacyLink': 'Privacy Policy',
    
    // Pricing
    'pricing.title': 'Simple, Credit-Based Pricing',
    'pricing.subtitle': 'Pay only for what you use. Credits never expire.',
    'pricing.creditSystem': '1 credit = 3 pages',
    'pricing.freeCredits': 'Every new user gets 15 free credits',
    'pricing.credits': 'credits',
    'pricing.pages': 'pages',
    'pricing.bestValue': 'Best Value',
    'pricing.buyNow': 'Buy Now',
    'pricing.perCredit': 'per credit',
    'pricing.features.title': 'What You Get',
    'pricing.features.aiPowered': 'AI-powered podcast generation',
    'pricing.features.naturalVoice': 'Natural-sounding text-to-speech',
    'pricing.features.multiLanguage': 'Multi-language support',
    'pricing.features.unlimitedSharing': 'Unlimited sharing & downloads',
    'pricing.features.noExpiry': 'Credits never expire',
    'pricing.features.support': 'Email support',
    'pricing.faq.title': 'Frequently Asked Questions',
    'pricing.faq.q1': 'How do credits work?',
    'pricing.faq.a1': '1 credit equals 3 pages of processing. For example, a 10-page PDF requires 4 credits (10 ÷ 3 = 3.33, rounded up to 4).',
    'pricing.faq.q2': 'Do credits expire?',
    'pricing.faq.a2': 'No! Credits never expire. Use them whenever you need.',
    'pricing.faq.q3': 'Can I get a refund?',
    'pricing.faq.a3': 'Yes, we offer a 30-day money-back guarantee if you\'re not satisfied.',
    'pricing.faq.q4': 'What payment methods do you accept?',
    'pricing.faq.a4': 'We accept all major credit cards via Stripe secure payment.',
    
    // Common
    'common.loading': 'Loading...',
    'common.or': 'or',
  },
  tr: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.getStarted': 'Başla',
    'nav.login': 'Giriş Yap',
    'nav.signup': 'Kayıt Ol',
    'nav.pricing': 'Fiyatlandırma',
    
    // Landing Page
    'landing.hero.title': 'Raporlarınızı',
    'landing.hero.podcast': "Podcast'e Dönüştürün",
    'landing.hero.subtitle': 'Uzun raporları artık okumak zorunda değilsiniz. ReportCast ile dokümanlarınız dinlenebilir podcast\'lere dönüşür.',
    'landing.hero.cta': 'Hemen Başla',
    'landing.hero.howItWorks': 'Nasıl Çalışır?',
    
    'landing.how.title': 'Nasıl Çalışır?',
    'landing.how.subtitle': '3 basit adımda raporlarınızı podcast\'e dönüştürün',
    'landing.how.step1.title': '1. Raporu Yükleyin',
    'landing.how.step1.desc': 'Raporunuzu PDF formatında yükleyin. 50 sayfaya kadar dokümanları destekliyoruz.',
    'landing.how.step2.title': '2. Podcast\'e Dönüştürün',
    'landing.how.step2.desc': 'Yapay zeka teknolojimiz raporunuzu doğal ve dinlenebilir bir podcast\'e dönüştürür.',
    'landing.how.step3.title': '3. Paylaşın',
    'landing.how.step3.desc': 'Oluşan public linki ekibinizle paylaşın. Herkes istediği zaman istediği yerden dinleyebilir.',
    
    'landing.features.title': 'Neden ReportCast?',
    'landing.features.subtitle': 'Öğrenmeyi daha erişilebilir hale getirin',
    'landing.features.listen.title': 'Her Yerde Dinleyin',
    'landing.features.listen.desc': 'Araç kullanırken, spor yaparken veya yolculukta - raporları artık her yerde dinleyebilirsiniz.',
    'landing.features.fast.title': 'Hızlı Dönüşüm',
    'landing.features.fast.desc': 'Yapay zeka destekli sistemimiz saniyeler içinde raporlarınızı profesyonel podcast\'lere dönüştürür.',
    'landing.features.secure.title': 'Güvenli Paylaşım',
    'landing.features.secure.desc': 'Public linklerle kontrollü paylaşım yapın. İstediğiniz zaman linkleri devre dışı bırakabilirsiniz.',
    
    'landing.cta.title': 'Hazır mısınız?',
    'landing.cta.subtitle': 'İlk raporunuzu podcast\'e dönüştürmek için hemen başlayın',
    'landing.cta.button': 'Ücretsiz Başla',
    
    'landing.footer': '© 2026 ReportCast. Tüm hakları saklıdır.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.upload.title': 'Yeni Rapor Yükle',
    'dashboard.upload.desc': 'Raporunuzu podcast\'e dönüştürün',
    'dashboard.upload.label': 'Rapor Dosyası',
    'dashboard.upload.placeholder': 'Dosya seçilmedi',
    'dashboard.upload.button': 'Yükle & Dönüştür',
    'dashboard.upload.success': 'Rapor başarıyla yüklendi! Podcast\'e dönüştürülüyor...',
    'dashboard.reports.title': 'Podcast\'leriniz',
    'dashboard.reports.status.pending': 'Beklemede',
    'dashboard.reports.status.processing': 'İşleniyor',
    'dashboard.reports.status.ready': 'Hazır',
    'dashboard.reports.status.completed': 'Tamamlandı',
    'dashboard.reports.status.failed': 'Başarısız',
    'dashboard.reports.duration': 'dk',
    'dashboard.reports.views': 'dinlenme',
    'dashboard.reports.share': 'Linki Paylaş',
    'dashboard.reports.listen': 'Dinle',
    'dashboard.reports.delete': 'Sil',
    'dashboard.copy.success': 'Paylaşım linki panoya kopyalandı!',
    'dashboard.delete.success': 'Podcast başarıyla silindi',
    'dashboard.confirm.title': 'İşlemi Onayla',
    'dashboard.confirm.message': 'Ücret',
    'dashboard.confirm.button': 'Onayla & İşle',
    
    // Podcast Player
    'podcast.backToDashboard': 'Dashboard\'a Dön',
    'podcast.generatedBy': 'ReportCast tarafından oluşturuldu',
    'podcast.share': 'Paylaş',
    'podcast.shareTitle': 'Bu Podcast\'i Paylaş',
    'podcast.shareDesc': 'Bu linke sahip olan herkes bu podcast\'i dinleyebilir',
    'podcast.copyLink': 'Linki Kopyala',
    'podcast.cancel': 'İptal',
    
    // Auth Pages
    'auth.login.title': 'Tekrar Hoş Geldiniz',
    'auth.login.subtitle': 'ReportCast hesabınıza giriş yapın',
    'auth.login.email': 'E-posta',
    'auth.login.password': 'Şifre',
    'auth.login.button': 'Giriş Yap',
    'auth.login.noAccount': 'Hesabınız yok mu?',
    'auth.login.signUp': 'Kayıt ol',
    'auth.login.forgotPassword': 'Şifremi unuttum?',
    
    'auth.signup.title': 'Hesap Oluştur',
    'auth.signup.subtitle': 'Raporları podcast\'e dönüştürmeye başlayın',
    'auth.signup.name': 'Ad Soyad',
    'auth.signup.email': 'E-posta',
    'auth.signup.password': 'Şifre',
    'auth.signup.confirmPassword': 'Şifre Tekrar',
    'auth.signup.button': 'Hesap Oluştur',
    'auth.signup.hasAccount': 'Zaten hesabınız var mı?',
    'auth.signup.signIn': 'Giriş yap',
    'auth.signup.terms': 'Kayıt olarak,',
    'auth.signup.termsLink': 'Kullanım Şartları',
    'auth.signup.and': 've',
    'auth.signup.privacyLink': 'Gizlilik Politikası',
    
    // Pricing
    'pricing.title': 'Basit, Kredi Tabanlı Fiyatlandırma',
    'pricing.subtitle': 'Sadece kullandığınız kadar ödeyin. Krediler asla sona ermez.',
    'pricing.creditSystem': '1 kredi = 3 sayfa',
    'pricing.freeCredits': 'Her yeni kullanıcıya 15 ücretsiz kredi verilir',
    'pricing.credits': 'kredi',
    'pricing.pages': 'sayfa',
    'pricing.bestValue': 'En İyi Değer',
    'pricing.buyNow': 'Şimdi Satın Al',
    'pricing.perCredit': 'kredi başına',
    'pricing.features.title': 'Ne Alıyorsunuz?',
    'pricing.features.aiPowered': 'Yapay zeka destekli podcast üretimi',
    'pricing.features.naturalVoice': 'Doğal sesli metin okuma',
    'pricing.features.multiLanguage': 'Çoklu dil desteği',
    'pricing.features.unlimitedSharing': 'Sınırsız paylaşım & indirme',
    'pricing.features.noExpiry': 'Krediler asla sona ermez',
    'pricing.features.support': 'E-posta desteği',
    'pricing.faq.title': 'Sık Sorulan Sorular',
    'pricing.faq.q1': 'Krediler nasıl çalışır?',
    'pricing.faq.a1': '1 kredi, 3 sayfa işleme karşılık gelir. Örneğin, 10 sayfalık bir PDF 4 kredi gerektirir (10 ÷ 3 = 3.33, yukarı yuvarlanarak 4).',
    'pricing.faq.q2': 'Krediler sona erer mi?',
    'pricing.faq.a2': 'Hayır! Krediler asla sona ermez. İhtiyacınız olduğunda kullanabilirsiniz.',
    'pricing.faq.q3': 'İade edebilir miyim?',
    'pricing.faq.a3': 'Evet, memnuniyetiniz sağlanmazsa 30 günlük para iadesi garantisi sunuyoruz.',
    'pricing.faq.q4': 'Hangi ödeme yöntemlerini kabul ediyorsunuz?',
    'pricing.faq.a4': 'Stripe güvenli ödeme yoluyla tüm büyük kredi kartlarını kabul ediyoruz.',
    
    // Common
    'common.loading': 'Yükleniyor...',
    'common.or': 'veya',
  },
};

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    // Load language from localStorage
    const savedLanguage = localStorage.getItem('incidentcast_language') as Language;
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'tr')) {
      setLanguageState(savedLanguage);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('incidentcast_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}